name: Functional Tests Pipeline - $(Build.DefinitionName) - $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
# References
# To create json schema: https://easy-json-schema.github.io/
# Newman: https://github.com/postmanlabs/newman

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../../../recipes/common/Variables.yml
#  - group: MLOPSVG

stages:
  - stage: RunFunctionalTests
    displayName: Run functional tests
    jobs:
      - template: ../../../recipes/ci/RunNewmanFunctionalTests.yml
        parameters:
          service_name: 'risk-model-aks'
          postman_collection_file: 'models/risk-model/tests/functional/risk_service_postman_collection.json'